@startuml
skinparam dpi 300
actor User
participant LoginPresenter as LP
participant LoggedInViewModel as LVM
participant LoggedInState as LS
participant PropertyChangeSupport as PCS
participant LoggedInView as LIV

activate LP
User -> LP : prepareSuccessView(LoginOutputData)
LP -> LVM : getState()
activate LVM
LVM --> LP : LoggedInState
deactivate LVM

LP -> LS : setUsername(response.getUsername())
activate LS
LS --> LP
deactivate LS

LP -> PCS : firePropertyChange()
activate PCS


PCS -> LIV : propertyChange(evt)
activate LIV

LIV -> LIV : update UI with LoggedInState

LIV --> PCS
deactivate LIV
PCS --> LP
deactivate PCS

... Diagram continues with LoginViewModel and ViewManager updates...


@enduml